### DISCUSSION TITLE
Which tag for Raspberry Pi and QNAP NAS?

### DISCUSSION THREAD

**Discussion by NetRat88** [nicholas-fedor/watchtower#254] [Support] [answered]
Dear @nicholas-fedor,

I already changed my docker-compose files to your new image without any trouble. But recently recognized your new [documantation](https://nicholas-fedor.github.io/watchtower/usage-overview/) and the following hint:

> Watchtower is itself packaged as a Docker container so installation is as simple as pulling the nickfedor/watchtower image. If you are using ARM based architecture, pull the appropriate nickfedor/watchtower:armhf-<tag> image from the [nickfedor Docker Hub](https://hub.docker.com/r/nickfedor/watchtower/tags/).

Does it mean for the Raspberry Pi's 3Plus, 4 & 5 I should use the image: nickfedor/watchtower:armhf ?
Currently I used for all my systems image: nickfedor/watchtower and didn't recognize any errors. What is the difference?

This is my current docker-compose.yaml:

```yaml
---
services:
  watchtower:
    image: nickfedor/watchtower
    container_name: watchtower
    hostname: Watchtower RPi 4 #RPi 4 durch entsprechenden Hostnamen anpassen, welcher z.B.: in Pushover Nachrichten angezeigt werden soll
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=Europe/Berlin
      - WATCHTOWER_SCHEDULE=0 50 0 * * *
      - WATCHTOWER_MONITOR_ONLY=false
      - WATCHTOWER_NOTIFICATION_URL=pushover://######################/?title=Watchtower&priority=1
      - WATCHTOWER_INCLUDE_STOPPED=true
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_INCLUDE_RESTARTING=true
      #- WATCHTOWER_POLL_INTERVAL=30
    restart: unless-stopped
```

Many thanks in advance and best regards
