### DISCUSSION TITLE
v1.10.0 problems?

### DISCUSSION THREAD

**Discussion by hle-pc** [nicholas-fedor/watchtower#284] [Support] [answered]
Anyone else have problems getting this to run with [1.10.0](https://github.com/nicholas-fedor/watchtower/releases/tag/v1.10.0)?

Rolling back to v1.9.2 works though

**Comment by waja** [comment]
@hle-pc Could you please get a bit more into details except 'it's broken'?

**Reply by hle-pc** [reply]
Unfortunately I don't have any. There are no logs at all.

This is why I'm asking if other people have issues.  Cause I don't have enough to report a problem on my own.

**Comment by nicholas-fedor** [comment, marked as answer]
I have 40+ instances of Watchtower running throughout my environment with notifications feeding to Gotify. 
This is using the following configuration within my Docker Compose files when running on various machines, including Ubuntu (24.10 and 25.04), Debian 12, and Alpine 3.21 VM's and LXC containers on AMD64 architecture. 
There have been no issues/abnormalities in the update from v1.9.2 to 1.10.1 for me. 

```yaml
...
  watchtower:
    container_name: watchtower
    environment:
      - DOCKER_REQUEST_TIMEOUT=120s
      - WATCHTOWER_SCHEDULE=0 0 */6 * * * # Every 6 hours
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_INCLUDE_STOPPED=true
      - WATCHTOWER_INCLUDE_RESTARTING=true
      - WATCHTOWER_REVIVE_STOPPED=true
      - WATCHTOWER_NOTIFICATIONS=gotify
      - WATCHTOWER_NOTIFICATION_GOTIFY_URL=https://gotify.${DOMAIN}/
      - WATCHTOWER_NOTIFICATION_GOTIFY_TOKEN=/run/secrets/WATCHTOWER_NOTIFICATION_GOTIFY_TOKEN
    healthcheck:
      test: ["CMD", "/watchtower", "--health-check"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    image: nickfedor/watchtower:latest
    networks:
      - watchtower
    restart: unless-stopped
    secrets:
      - WATCHTOWER_NOTIFICATION_GOTIFY_TOKEN
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
...
```

Note that the minor version increment was based on a simple addition of a memory swappiness flag for Podman support.
The only other change of note was reducing the logging level for shutdown signals and context cancellation. 

My recommendation would be to evaluate your configuration of Watchtower and/or your underlying infrastructure.
This can be best accomplished by ensuring you have reviewed the [documentation](https://nicholas-fedor.github.io/watchtower/).
Feel free to share your setup here if you have questions regarding how to properly setup Watchtower.

If you continue to see issues, then I highly recommend doing a single update run of Watchtower with debug logging enabled. 
Then, submit an issue using the predefined template and make sure to include the debug logs.
There is a vested interest into ensuring Watchtower performs as intended; however, that also means providing the information necessary to identify and resolve issues.
