### ISSUE TITLE
stumbling with v1.11.0 release (Detected multiple Watchtower instances)

### ISSUE THREAD

**Issue by bondskin** [nicholas-fedor/watchtower#307]
### Describe the bug

Hi,

not sure if this is potentially related to a (stopped) separated watchtower container running for scrypted.
But your watchtower update caused some errors here today.

1st notification:
> Found new image: nickfedor/watchtower:latest (d96d286cf6f9)
> Started new container: /watchtower (5756cb3a0c9f)
> Updated container | container=/watchtowerimage=nickfedor/watchtower:latest
> Removed stale image: 92004ae6c8b2
> Failed to remove image | error=failed to remove image: sha256:92004ae6c8b29994a92048321ad80006c2aee21356665505901dbdd66ae25278: Error response from daemon: conflict: unable to delete 92004ae6c8b2 (cannot be forced) - image is being used by running container 87b6c1e9085cimage_id=sha256:92004ae6c8b29994a92048321ad80006c2aee21356665505901dbdd66ae25278

2nd notification:
> Detected multiple Watchtower instances, initiating cleanup | count=2
> Stopping excess Watchtower instances | containers=[BHxWSZNPCzDgYuRadQqsHfsibsgyTOIT]
> Stopped stale container: BHxWSZNPCzDgYuRadQqsHfsibsgyTOIT (87b6c1e9085c)
> Stopped Watchtower instance | container=BHxWSZNPCzDgYuRadQqsHfsibsgyTOIT
> Removed stale image: 92004ae6c8b2
> Successfully cleaned up excess Watchtower instances
> Watchtower 1.11.0 using Docker API v1.50
> Using notifications: smtp
> Checking all containers (except explicitly disabled with label)
> Scheduling first run: 2025-06-09 11:22:33 +0200 CEST
> Note that the first check will be performed in 23 hours, 59 minutes, 59 seconds

compose config:
 ```
---
version: "3"
services:
  watchtower:
    image: nickfedor/watchtower
    container_name: watchtower
    command: --stop-timeout 300s  # --debug
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro

   environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=86400  # 1x pro Tag (in Sekunden)
      - WATCHTOWER_NOTIFICATIONS=email
      - WATCHTOWER_NOTIFICATION_EMAIL_FROM=xxx
      - WATCHTOWER_NOTIFICATION_EMAIL_TO=xxx
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER=smtp.gmail.com
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT=587
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER=xxx
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD=${EMAIL_PASSWORD}
      - WATCHTOWER_INCLUDE_RESTARTING=true
      - WATCHTOWER_ROLLING_RESTART=true
      # - WATCHTOWER_MONITOR_ONLY=true

    restart: always

    network_mode: host
    privileged: true
```
    

### Steps to reproduce

not able

### Expected behavior

not having multiple instances

### Environment

- Pi4
- arm64
- Docker version 28.2.2, build e6534b4

### Your logs

```text
time="2025-06-08T11:22:32+02:00" level=info msg="Detected multiple Watchtower instances, initiating cleanup" count=2
time="2025-06-08T11:22:32+02:00" level=info msg="Stopping excess Watchtower instances" containers="[BHxWSZNPCzDgYuRadQqsHfsibsgyTOIT]"
time="2025-06-08T11:22:32+02:00" level=info msg="Stopping container" container=BHxWSZNPCzDgYuRadQqsHfsibsgyTOIT id=87b6c1e9085c signal=SIGTERM
time="2025-06-08T11:22:33+02:00" level=info msg="Stopped Watchtower instance" container=BHxWSZNPCzDgYuRadQqsHfsibsgyTOIT
time="2025-06-08T11:22:33+02:00" level=info msg="Removing image" image_id=92004ae6c8b2
time="2025-06-08T11:22:33+02:00" level=info msg="Successfully cleaned up excess Watchtower instances"
time="2025-06-08T11:22:33+02:00" level=info msg="Watchtower 1.11.0 using Docker API v1.50"
time="2025-06-08T11:22:33+02:00" level=info msg="Using notifications: smtp"
time="2025-06-08T11:22:33+02:00" level=info msg="Checking all containers (except explicitly disabled with label)"
time="2025-06-08T11:22:33+02:00" level=info msg="Scheduling first run: 2025-06-09 11:22:33 +0200 CEST"
time="2025-06-08T11:22:33+02:00" level=info msg="Note that the first check will be performed in 23 hours, 59 minutes, 59 seconds"
```

**Comment by waja** [comment]
Looks not new related to the latest release. Spotted this on some systems in the past, but seems not to harm anything.

**Comment by nicholas-fedor** [comment]
This is normal behavior when Watchtower is self-updating.
The logging just needs some additional fine-tuning.

**Comment by bondskin** [comment]
Thanks @waja , @nicholas-fedor ,
All good, I did not encounter this before,

**Comment by nicholas-fedor** [comment]
@bondskin 
After doing some digging, it turned out to be a bug in the original codebase that led to a race condition when Watchtower was self-updating. My latest release (v1.11.3) should hopefully alleviate this bug and the error / warning message that was generated from it.

**Comment by CyreX541** [comment]
Still present with v1.11.6, running multiple instances separated in different scopes.
The first one started at first will be terminated by second regardless of difference of their scope name. ( ScopeA or ScopeB or ScopeC)

The respective scope gets acknowledged by their regarding instance by 'Only checking containers in scope "CorrectScopeForEachInstance"'

**Comment by bondskin** [comment]
This is what I got 

Detected multiple Watchtower instances, initiating cleanup | count=2
Stopped stale container: JausTwDVnwRWNDponEQkmRSBtiyAqcDt (da151dc15dec)
Removed stale image: 66a2b1fdac53
Successfully cleaned up excess Watchtower instances
Watchtower 1.11.6 using Docker API v1.51
Using notifications: smtp
Checking all containers (except explicitly disabled with label)
Scheduling first run: 2025-07-18 14:24:36 +0200 CEST
Note that the first check will be performed in 23 hours, 59 minutes, 59 seconds

**Comment by CyreX541** [comment]
This are my logs.
Container 1:
```
cyrex-wt-manual  | time="2025-07-19T21:52:58+02:00" level=info msg="Watchtower 1.11.6 using Docker API v1.51"
cyrex-wt-manual  | time="2025-07-19T21:52:58+02:00" level=info msg="Using notifications: smtp"
cyrex-wt-manual  | time="2025-07-19T21:52:58+02:00" level=info msg="Only checking containers in scope \"'cyrex-wt-manual'\""
cyrex-wt-manual  | time="2025-07-19T21:52:58+02:00" level=info msg="Scheduling first run: 2025-07-20 00:45:00 +0200 CEST"
cyrex-wt-manual  | time="2025-07-19T21:52:58+02:00" level=info msg="Note that the first check will be performed in 2 hours, 52 minutes, 1 second"
```

Container 2:
```
cyrex-wt-auto    | time="2025-07-19T21:52:58+02:00" level=info msg="Detected multiple Watchtower instances, initiating cleanup" count=2
cyrex-wt-auto    | time="2025-07-19T21:52:58+02:00" level=info msg="Stopping container" container=cyrex-wt-auto id=765bd3b17e8c signal=SIGTERM
cyrex-wt-auto exited with code 2
```

**Comment by CyreX541** [comment]
This config works when used with the containrrr/watchtower image.
Heres my compose.yml
```
services:

  cyrex-wt-auto:
    image: "nickfedor/watchtower"
    hostname: "cyrex-wt-auto"
    container_name: "cyrex-wt-auto"
    restart: "always"
    labels:
      - "com.centurylinklabs.watchtower.scope=cyrex-wt-auto"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - "TZ=Europe/Berlin"
      - "WATCHTOWER_SCHEDULE=0 30 0/12 * * *"
      - "WATCHTOWER_CLEANUP=true"
      - "WATCHTOWER_MONITOR_ONLY=false"
      - "WATCHTOWER_ROLLING_RESTART=true"
      - "WATCHTOWER_TIMEOUT=20s"
      - "WATCHTOWER_NOTIFICATIONS=email"
      - "WATCHTOWER_NOTIFICATIONS_LEVEL=info"
      - "WATCHTOWER_NOTIFICATION_EMAIL_FROM=*redacted*"
      - "WATCHTOWER_NOTIFICATION_EMAIL_TO=*redacted*"
      - "WATCHTOWER_NOTIFICATION_EMAIL_SERVER=*redacted*"
      - "WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT=*redacted*"
      - "WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER=*redacted*"
      - "WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD=*redacted*"
      - "WATCHTOWER_NOTIFICATION_EMAIL_SUBJECTTAG=*redacted*"
    networks:
      - "cyrex-wt"

  cyrex-wt-manual:
    image: "nickfedor/watchtower"
    hostname: "cyrex-wt-manual"
    container_name: "cyrex-wt-manual"
    restart: "always"
    labels:
      - "com.centurylinklabs.watchtower.scope=cyrex-wt-manual"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - "TZ=Europe/Berlin"
      - "WATCHTOWER_SCHEDULE=0 45 0/12 * * *"
      - "WATCHTOWER_CLEANUP=false"
      - "WATCHTOWER_MONITOR_ONLY=true"
      - "WATCHTOWER_ROLLING_RESTART=false"
      - "WATCHTOWER_TIMEOUT=20s"
      - "WATCHTOWER_NOTIFICATIONS=email"
      - "WATCHTOWER_NOTIFICATIONS_LEVEL=info"
      - "WATCHTOWER_NOTIFICATION_EMAIL_FROM=*redacted*"
      - "WATCHTOWER_NOTIFICATION_EMAIL_TO=*redacted*"
      - "WATCHTOWER_NOTIFICATION_EMAIL_SERVER=*redacted*"
      - "WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT=*redacted*"
      - "WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER=*redacted*"
      - "WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD=*redacted*"
      - "WATCHTOWER_NOTIFICATION_EMAIL_SUBJECTTAG=*redacted*"
    networks:
      - "cyrex-wt"

networks:

  cyrex-wt:
    driver: "bridge"
    enable_ipv6: true
    name: "cyrex-wt"
    ipam:
      driver: "default"
      config:
        - subnet: "*redacted*"
        - subnet: "*redacted*"
```
